
#  * Created Date: Tuesday July 13th 2021 8:39:31 pm
#  * Author: Andrés X. Vargas
#  * -----
#  * Last Modified: Tuesday July 13th 2021 8:39:32 pm
#  * Modified By: the developer known as Andrés X. Vargas at <axvargas@fiec.espol.edu.ec>
#  * -----
#  * Copyright (c) 2021 MattuApps
#  *
news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries: 
      homepage_article_links: '.titulo a'
      article_body: '.field.field-name-body'
      article_title: '.Encabezado-Articulo h1'
  elpais:
    url: https://elpais.com
    queries: 
      homepage_article_links: 'h2 > a'
      article_body: '#ctn_article_body > p'
      article_title: '#article_header h1'